# Generated by Django 5.0.2 on 2024-03-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musician.musician'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='Album_Name',
            field=models.CharField(max_length=50),
        ),
    ]
