# Generated by Django 5.0.2 on 2024-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_album_musician_alter_album_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.IntegerField(choices=[('1', 'bad'), ('2', 'not good'), ('3', 'good'), ('4', 'better'), ('5', 'best')]),
        ),
    ]
