# Generated by Django 5.0.2 on 2024-03-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0004_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
